"""ForecastMethod

Revision ID: 1c745f2fae23
Revises: c7801567409a
Create Date: 2024-09-27 17:19:14.083644

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1c745f2fae23"
down_revision: Union[str, None] = "c7801567409a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "forecast_methods",
        sa.Column("alias", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("alias"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("forecast_methods")
    # ### end Alembic commands ###
