"""PriceSql has value instead of price

Revision ID: 2693593566d4
Revises: 684e7462e977
Create Date: 2024-09-29 18:00:50.264761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2693593566d4'
down_revision: Union[str, None] = '684e7462e977'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prices', sa.Column('value', sa.Float(), nullable=False))
    op.drop_column('prices', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prices', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('prices', 'value')
    # ### end Alembic commands ###
