"""PNodes have time zones

Revision ID: 44f3c18207e8
Revises: 2693593566d4
Create Date: 2024-09-30 01:13:06.344482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44f3c18207e8'
down_revision: Union[str, None] = '2693593566d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
     op.add_column('p_nodes', sa.Column('tz', sa.String(), nullable=False, server_default='America/New_York'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('p_nodes', 'tz')
    # ### end Alembic commands ###
