"""Price

Revision ID: 9eeb1aa1a9f4
Revises: b64886b92189
Create Date: 2024-09-27 17:13:36.099870

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9eeb1aa1a9f4"
down_revision: Union[str, None] = "b64886b92189"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prices",
        sa.Column("market_slot_name", sa.String(), nullable=False),
        sa.Column("market_name", sa.String(), nullable=False),
        sa.Column("slot_start_s", sa.Integer(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["market_name"],
            ["markets.name"],
        ),
        sa.PrimaryKeyConstraint("market_slot_name"),
        sa.UniqueConstraint(
            "market_name", "slot_start_s", name="uq_from_market_and_start"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("prices")
    # ### end Alembic commands ###
