"""HourlyPriceForecasts

Revision ID: b4a248d88198
Revises: e058ab8233a1
Create Date: 2024-09-27 17:23:56.633063

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b4a248d88198"
down_revision: Union[str, None] = "e058ab8233a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hourly_forecasts",
        sa.Column("price_uid", sa.String(), nullable=False),
        sa.Column("from_g_node_alias", sa.String(), nullable=False),
        sa.Column("channel_name", sa.String(), nullable=False),
        sa.Column("start_unix_s", sa.Integer(), nullable=False),
        sa.Column(
            "hour_starting_prices",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("forecast_created_s", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["channel_name"],
            ["hpf_channels.name"],
        ),
        sa.PrimaryKeyConstraint("price_uid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("hourly_forecasts")
    # ### end Alembic commands ###
