"""Market

Revision ID: b64886b92189
Revises: 0d06cb9c4fa1
Create Date: 2024-09-27 17:06:23.493967

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b64886b92189"
down_revision: Union[str, None] = "0d06cb9c4fa1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "markets",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("market_type_name", sa.String(), nullable=False),
        sa.Column("p_node_alias", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("unit", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["p_node_alias"],
            ["p_nodes.alias"],
        ),
        sa.PrimaryKeyConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("markets")
    # ### end Alembic commands ###
