"""Add iso info to pnode

Revision ID: c444bd3cd979
Revises: b4a248d88198
Create Date: 2024-09-28 10:34:13.756624

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c444bd3cd979"
down_revision: Union[str, None] = "b4a248d88198"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "market_uq_type_pn_cat",
        "markets",
        ["market_type_name", "p_node_alias", "category"],
    )
    op.add_column("p_nodes", sa.Column("iso_location_info", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("p_nodes", "iso_location_info")
    op.drop_constraint("market_uq_type_pn_cat", "markets", type_="unique")
    # ### end Alembic commands ###
