"""LatestPrediction

Revision ID: c7801567409a
Revises: 9eeb1aa1a9f4
Create Date: 2024-09-27 17:17:31.549601

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c7801567409a"
down_revision: Union[str, None] = "9eeb1aa1a9f4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "latest_predictions",
        sa.Column("market_slot_name", sa.String(), nullable=False),
        sa.Column("market_name", sa.String(), nullable=False),
        sa.Column("slot_start_s", sa.Integer(), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column("last_updated_s", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["market_name"],
            ["markets.name"],
        ),
        sa.PrimaryKeyConstraint("market_slot_name"),
        sa.UniqueConstraint(
            "market_name", "slot_start_s", name="uq_prediction_from_market_and_start"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("latest_predictions")
    # ### end Alembic commands ###
