"""HourlyPriceForecastChannel

Revision ID: e058ab8233a1
Revises: 1c745f2fae23
Create Date: 2024-09-27 17:21:20.242681

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e058ab8233a1"
down_revision: Union[str, None] = "1c745f2fae23"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hpf_channels",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("market_name", sa.String(), nullable=False),
        sa.Column("total_hours", sa.Integer(), nullable=False),
        sa.Column("method_alias", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["market_name"],
            ["markets.name"],
        ),
        sa.ForeignKeyConstraint(
            ["method_alias"],
            ["forecast_methods.alias"],
        ),
        sa.PrimaryKeyConstraint("name"),
        sa.UniqueConstraint(
            "market_name",
            "total_hours",
            "method_alias",
            name="uq_from_market, hrs, method",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("hpf_channels")
    # ### end Alembic commands ###
