"""Add unique constraint for forecasts

Revision ID: f9118269f440
Revises: c444bd3cd979
Create Date: 2024-09-28 16:34:19.754438

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f9118269f440"
down_revision: Union[str, None] = "c444bd3cd979"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "forecast_uq_channel_start_created",
        "hourly_forecasts",
        ["channel_name", "start_unix_s", "forecast_created_s"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "forecast_uq_channel_start_created", "hourly_forecasts", type_="unique"
    )
    # ### end Alembic commands ###
